### ISSUE TITLE
manglende visning af visse former for hi-opmærkning

### ISSUE THREAD

**Issue by fgredal** [dsldk/dsl-tei#19]
tekst opmærket med `<hi rend="small">` vises ikke (er usynlig!)

`<hi rend="strong"`> (ville man forvente 'bold' i stedet for strong?) vises ikke.

eksempler findes i opmærkningen af oersted-hc_aanden_i_naturen-1.xml  og ditto  -2.xml

**Comment by thsh77** [comment]
Dette synes at fungere nu. Sagen lukkes.
