### ISSUE TITLE
Kritiske noter indlejres under samme tekst

### ISSUE THREAD

**Issue by ASDSL** [dsldk/dsl-tei#24]
Tekstkritiske noter vises altid efter teksten; det er upraktisk, da man risikerer at scrolle langt. 

Det vil være bedre hvis disse vises umiddelbart _efter_ hver tekst.

**Comment by thsh77** [comment]
Tekstkritisk noter er med https://github.com/dsldk/dsl-tei/commit/bdbff3451f408cb1afe681937ba2f705c247ad69 flyttet hen under den enkelte tekst. Sagen lukkes.
