### ISSUE TITLE
Elementer genereret af xslt er ikke i HTML-namespace

### ISSUE THREAD

**Issue by axgeertinger** [dsldk/dsl-tei#6]
Elementer er uden namespace. Det giver problemer, når jeg f.eks. transformerer i xquery og sender resultatet til browseren. Hvis jeg kører resultatet gennem endnu en transformation, der omskriver alle elementer til namespace http://www.w3.org/1999/xhtml, fungerer det.

**Comment by thsh77** [comment]
Vi bliver nok nødt til at se på det sammen, hvis jeg skal forstå problemet. Jeg har bevidst valgt at lave HTML5 (som ikke er XML) ud af transformationen, og det kan Oxygen ikke finde ud af.

**Comment by axgeertinger** [comment]
Jeg ser problemet, hvis jeg bruger xquery i eXist til transformationen. Jeg kan vise dig det ved lejlighed. Måske er der også bare noget, jeg har overset. Det haster ikke.

**Comment by thsh77** [comment]
Hvad skal du bruge Xquery og eXist til?

**Comment by axgeertinger** [comment]
OK, jeg fik løst det. Problemet var, at jeg ikke kunne få selve transformationen til at lave en "DOCTYPE html"-erklæring. Men tricket var at sætte det som en option i xquery i stedet:
`declare option exist:serialize "method=html5 media-type=text/html"; `
Jeg bruger det til at forsøge at undgå at skulle bruge Saxon som kommandlinjeværktøj for at generere et html-"preview" af Thomissøn & co. Det er lidt for bøvlet, synes jeg, især mens jeg implementerer tei:notatedMusic og skal afprøve resultatet hele tiden. Så jeg har lavet denne: 
[http://salmer.dsl.lan:8080/exist/rest/db/tools/html/preview.xq](http://salmer.dsl.lan:8080/exist/rest/db/tools/html/preview.xq)
